Repository dwyl/elixir-auth-google, pull requests merged in 2019-12, with the labels that each got.

#18 Detect host url from conn struct and derive google_redirect_uri issue #17
  lib/elixir_auth_google.ex
  mix.exs
  test/elixir_auth_google_test.exs
Labels: awaiting-review, enhancement

#21 Add sensible defaults to the project config.exs
  config/config.exs
Labels: awaiting-review

#11 PR: Documentation
  .env_sample
  .gitignore
  .travis.yml
  README.md
  config/config.exs
  create-google-app-guide.md
  lib/elixir_auth_google.ex
  lib/httpoison/in_memory.ex
  mix.exs
  mix.lock
  test/elixir_auth_google_test.exs
Labels: awaiting-review, documentation, enhancement

#23 add config/config.exs to hex package issue #19
  mix.exs
Labels: awaiting-review, chore, enhancement

#24 Update config
  config/config.exs
  lib/elixir_auth_google.ex
  mix.exs
Labels: awaiting-review

#27 update hex.pm badge to link to package fixes #26
  README.md
Labels: in-review
