Repository dwyl/elixir-auth-google, pull requests merged in 2021-10, with the labels that each got.

#46 update dependencies and Elixir version
  .travis.yml
  mix.exs
  mix.lock
Labels: awaiting-review

#40 Read CLIENT_ID and CLIENT_SECRET from Config when not available on system environment
  README.md
  config/config.exs
  config/test.exs
  create-google-app-guide.md
  lib/elixir_auth_google.ex
  mix.exs
  test/elixir_auth_google_test.exs
Labels: in-progress

#47 version 1.5.1
  mix.exs
Labels: question
