Repository dwyl/elixir-auth-google, pull requests merged in 2023-01, with the labels that each got.

#76 Update ci.yml file to user available elixir version
  .github/workflows/ci.yml
  README.md
  config/test.exs
  mix.exs
  test/elixir_auth_google_test.exs
Labels: in-review

#77 Update dependencies and dependabot.yml
  .github/dependabot.yml
  mix.exs
  mix.lock
Labels: awaiting-review

#75 feat: more robust host config
  lib/elixir_auth_google.ex
  test/elixir_auth_google_test.exs
Labels: enhancement, help wanted, T25m, awaiting-review, user-feedback, chore, technical

#78 Allow custom query params to oauth url generator
  lib/elixir_auth_google.ex
  test/elixir_auth_google_test.exs
Labels: awaiting-review
